# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install coverage
        pip install -r requirements.txt
        pip install platipy
        pip install numpy
    - name: Install elastix
      run: |
        wget -P ~/ElastixDownload "https://github.com/SuperElastix/elastix/releases/download/5.0.1/elastix-5.0.1-linux.tar.bz2"
        tar -xvf /home/runner/ElastixDownload/elastix-5.0.1-linux.tar.bz2
        ls /home/runner
        ls ~/ElastixDownload
        PATH=$PATH:~/elastix-5.0.1-linux/bin/elastix
        whereis elastix.exe
        which elastix.exe                
        #ls ~/elastix-5.0.1-linux/bin/elastix
        #ls ~/ElastixDownload/elastix-5.0.1-linux/bin/elastix

    - name: Test with pytest & Coverage
      run: |
        #pytest --cov-report xml --cov=CTHeadDeformation/
        coverage run -m pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
